name: black_coffer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  otp_text_field: ^1.1.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  image_picker: ^1.0.2
  cached_video_preview: ^1.0.6
  geolocator: ^10.0.0
  intl: ^0.18.1
  geocoding: ^2.1.0
  video_player: ^2.7.0
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3
  chewie: ^1.7.0
  google_fonts: ^4.0.0
  liquid_progress_indicator_v2: ^0.5.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
 
  